- name: Install and Configure Database
  apt:
    name: {{ item }}
    state: present
  with_items:
    - mysql-server
    - mysql-client

- name: Start Database Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: '{{ db_name }}'
    state: present

- name: Create database user
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    priv: '*.*:ALL'
    state: present
